### ISSUE TITLE
模型导出ONNX

### ISSUE THREAD

**Issue by xiaoqingzheng** [zkyseu/O2SFormer#1]
请问模型是否能够导出为ONNX，我尝试了一下没有导出成功。后续是否会支持模型导出为ONNX？

**Comment by zkyseu** [comment]
您好，目前O2SFormer还未尝试ONNX，最近我在忙于其他项目，我后续会试一下。您可以参考一下[mmdeploy](https://github.com/open-mmlab/mmdeploy)，里面有openmmlab系列模型的导出、c++、TensorRT等的demo。

**Comment by xiaoqingzheng** [comment]
好的，我再尝试一下mmdeploy，感谢您的回复
