### ISSUE TITLE
训练时，车道线起点表示问题

### ISSUE THREAD

**Issue by guvcolie** [zkyseu/O2SFormer#10]
您好，请问 https://github.com/zkyseu/O2SFormer/blob/main/dnlane/datasets/pipelines/lane_formating.py#L695 以下两行，分别表示车道线起点的Y坐标&X坐标，但lanes[lane_idx, 2] = len(xs_outside_image) / self.n_strips表示的Y值是什么含义呢？xs_outside_image表示的是在图像外 等Y线上X的坐标序列，self.n_strips实际就是71，那这两个数相除的含义是什么呢？lanes[lane_idx, 3] = xs_inside_image[0]我理解是车道线起点的实际X方向的像素坐标值。 lanes[lane_idx, 2]、lanes[lane_idx, 3]这两个数字的量纲明显不同，请解答一下，谢谢！

**Comment by zkyseu** [comment]
@guvcolie 相除表示将纵轴72等分，然后每一个等分上寻找对应车道线点，也就是说我们把车道线沿着y轴平均分成72个点。72个点相连便可形成车道线。
