### ISSUE TITLE
代码细节问题

### ISSUE THREAD

**Issue by guvcolie** [zkyseu/O2SFormer#11]
您好，这两句看起来是不是有问题
https://github.com/zkyseu/O2SFormer/blob/main/dnlane/models/detection_headv2.py#L159
https://github.com/zkyseu/O2SFormer/blob/main/dnlane/models/detection_headv2.py#L163
第163行把157～159行的结果直接覆盖了

**Comment by zkyseu** [comment]
157~159这几行代码其实是不需要的，因为reference在之前已经更新过了，但是我上传代码时候忘记将这部分给注释了。
