### ISSUE TITLE
batchsize > 1时，loss、grad_norm异常问题

### ISSUE THREAD

**Issue by guvcolie** [zkyseu/O2SFormer#12]
您好，之前开了一个issue请教您loss、grad_norm异常的问题  #6 ，我排除了自己数据集的问题，确保dataloader及数据增强是和culane逻辑完全一致了，最后发现当batchsize=1时，在自己数据集上loss收敛正常，但batchsize>1时，grad_norm很容易就好几万、loss下降到一定程度就不降了。
我注意到原始代码中 https://github.com/zkyseu/O2SFormer/blob/main/dnlane/models/detection_headv2.py#L245 这行的注释 “计算单个batch的损失, 因为直接计算整个batchsize会导致loss异常”，感觉这里还是有一些问题，可能culane数据集相对简单，batchsize>1也正常收敛了，但对于城市自动驾驶场景车道线数据，这个问题看起来还是存在

**Comment by zkyseu** [comment]
@guvcolie 您好，这个问题可能是代码实现的方式存在问题。因为我当时实现代码的时候也参考了CLRNet的loss部分，但是发现如果直接计算整个batchsize就一定会导致loss异常，我当时也没有发现为何导致的，但是如果一个一个地计算loss，这个时候loss就正常了，所以就加了这行注释。如果您有解决这个问题方法可以PR一下，我可以将您地方法merge进项目中，谢谢！

**Comment by zkyseu** [comment]
@guvcolie 如果您有其他问题可以重新打开issue，我先暂时关闭该issue哈。

**Comment by guvcolie** [comment]
> @guvcolie 您好，这个问题可能是代码实现的方式存在问题。因为我当时实现代码的时候也参考了CLRNet的loss部分，但是发现如果直接计算整个batchsize就一定会导致loss异常，我当时也没有发现为何导致的，但是如果一个一个地计算loss，这个时候loss就正常了，所以就加了这行注释。如果您有解决这个问题方法可以PR一下，我可以将您地方法merge进项目中，谢谢！

您上面说的“直接计算整个batchsize就一定会导致loss异常”，这个“异常”具体是指什么？ loss数值很大？还是nan？还是其他现象呢

**Comment by zkyseu** [comment]
异常是指loss很大，同时grad norm也很大，这个应该是和程序实现有关。

**Comment by guvcolie** [comment]
> 异常是指loss很大，同时grad norm也很大，这个应该是和程序实现有关。

您描述的这个现象和我这边的现象完全一样😭 我这边又详细测试了一下，batchsize在[1,6]之间都正常，batchsize=7有一定比例的iter出现grad_norm暴涨，batchsize=8必出loss、grad-norm问题。感觉很奇怪，我也再排查下

**Comment by zkyseu** [comment]
嗯嗯，我最近在忙于其他项目，如果您找到了合适的解决方法可以直接PR，我将您的改进融合进项目，谢谢！
