### ISSUE TITLE
语义分割loss bug

### ISSUE THREAD

**Issue by guvcolie** [zkyseu/O2SFormer#13]
您好，代码中我看seg支路的loss函数用的是CrossEntropyLoss，这个类的源代码中对于prediction是没有做 log_softmax的，需要我们在外层代码中做，但我看你的代码中好像没有做，这里是不是个bug？

**Comment by zkyseu** [comment]
@guvcolie CrossEntropyLoss在mmdetection中的实现在[这里](https://github.com/open-mmlab/mmdetection/blob/main/mmdet/models/losses/cross_entropy_loss.py)，可以看到交叉熵是F.cross_entropy这个函数。这个函数已经结合了log_softmax。
