### ISSUE TITLE
复现精度相差较大

### ISSUE THREAD

**Issue by GreatZeZuo** [zkyseu/O2SFormer#19]
你好用ResNet50复现实验结果，但是比论文中差了近一个点（76.8x），跑了两次都是这个结果，请问训练策略，设备对结果的影响大吗?

**Comment by zkyseu** [comment]
@GreatZeZuo 您好，先确认一下使用预训练权重时候，模型evaluation的F1 score是不是和论文里面对齐，这样保证环境基本上是正确的，其次，看一下学习率是不是和之前提供的log一致。这里其实有个小tricks，就是模型config里面可以设置50轮，然后在20论时候kill掉训练，保证训练是20轮，因为50轮的学习下降没有20轮那么快

**Comment by GreatZeZuo** [comment]
使用预训练权重和论文里是一样的。请问关于您说的kill后面的训练具体在代码里怎么做

**Comment by zkyseu** [comment]
将训练轮数改成50，在[这里](https://github.com/zkyseu/O2SFormer/blob/1abff3a529f2327c528663e5a538c556657ae8b0/configs/resnet_50_culane.py#L118)，然后在21轮数时候手动kill，或者设置一个程序在21轮时候kill掉训练。

**Comment by GreatZeZuo** [comment]
还可以这样吗？能不能在学习策略上做修改使其下降慢一点

**Comment by zkyseu** [comment]
或者您直接训练50个epoch，然后看一下整体的效果，然后取出第20个epoch结果也是可以的。

**Comment by GreatZeZuo** [comment]
还可以这样吗？请问有方法修改学习策略使其下降慢一些吗

**Comment by zkyseu** [comment]
建议您可以先试试完整训练50epoch时候效果，然后再考虑修改一些optimize中学习率调整的参数。

**Comment by GreatZeZuo** [comment]
好的我试试， 50epoch要训好久
