### ISSUE TITLE
关于CULane_metric

### ISSUE THREAD

**Issue by GreatZeZuo** [zkyseu/O2SFormer#20]
![1703684465121](https://github.com/zkyseu/O2SFormer/assets/99953881/73fdf943-a354-4a4e-ac0f-576e72352d18)
![1703684709250](https://github.com/zkyseu/O2SFormer/assets/99953881/a22cac1c-a3cd-4d67-9c4a-d4034339c11f)

文中在8个场景中的F1得分均高于CLRNet，为什么最后的得分却差了两个点？除了cross场景下的FP，它应该不参与F1的计算吧。

**Comment by zkyseu** [comment]
@GreatZeZuo 这个也是我当时诧异的点，cross的FP应该是参与的，不然不会得分比CLRNet低。

**Comment by zkyseu** [comment]
@GreatZeZuo 这个问题也是可以后续思考一下的，因为O2SFormer的cross场景下的FP比较高，也就是误检率比较高，需要未来去解决的

**Comment by GreatZeZuo** [comment]
代码里F1计算没有cross情形下FP吧，是直接记为0的。DETR有什么办法降低误检率吗？

**Comment by zkyseu** [comment]
@GreatZeZuo (1)其实目前O2SFormer还有超参数需要优化，例如图像增强等。具体什么方法其实还是需要去实验的

**Comment by GreatZeZuo** [comment]
> 代码里F1计算没有cross情形下FP吧，是直接记为0的。DETR有什么办法降低误检率吗？

不知道我的理解是不是有问题，在CUlane_metric里貌似是将cross下的F1得分全部计算为0

**Comment by zkyseu** [comment]
@GreatZeZuo 我看了好像是算的。但是这个指标上也看得出cross的FP较高问题可以后续研究解决
