### ISSUE TITLE
query可否不按CLRNet的prior进行初始化

### ISSUE THREAD

**Issue by ztianlin** [zkyseu/O2SFormer#21]
您好，请问本工作中在初始化车道线query时，可否不按照clrnet那样进行呢，能否只是简单地初始化四个空的query（没有起始点、角度这些先验），谢谢。

**Comment by zkyseu** [comment]
@ztianlin 您好，query的简单初始化是可以的，即不需要这些先验。最后预测时候是需要预测角度，起始点这些量来准备最后的检测结果。如果简单初始化的方式会导致收敛比较慢，毕竟是缺少了先验信息。当然不排除有更好地初始化方式。

**Comment by ztianlin** [comment]
十分有帮助和高效的回答，谢谢！
