### ISSUE TITLE
Lane2Seq Code

### ISSUE THREAD

**Issue by Mollylulu** [zkyseu/O2SFormer#22]
Thanks for sharing your new work Lane2Seq. Could you please share the expected release date for the code of this new work? Thank you!

**Comment by zkyseu** [comment]
Hi@Mollylulu, sorry for the late reply. Thanks for your interest in our work. I was busy with my ECCV paper.  The release date may be after the ECCV deadline.

**Comment by Mollylulu** [comment]
Noted. Thanks for your kind reply and looking forward to your code :)

**Comment by zkyseu** [comment]
The implementation is similar to Pix2seq and you can refer to it.
