### ISSUE TITLE
Unexpected key in source state_dict while load model.pth 

### ISSUE THREAD

**Issue by Hxiangdou** [zkyseu/O2SFormer#23]
The model and loaded state dict do not match exactly

unexpected key in source state_dict: ema_backbone_conv1_weight, ema_backbone_bn1_weight, ema_backbone_bn1_bias, ema_backbone_bn1_running_mean, ema_backbone_bn1_running_var, ema_backbone_bn1_num_batches_tracked, ema_backbone_layer1_0_conv1_weight, ema_backbone_layer1_0_bn1_weight, ema_backbone_layer1_0_bn1_bias, ema_backbone_layer1_0_bn1_running_mean, ema_backbone_layer1_0_bn1_running_var, ema_backbone_layer1_0_bn1_num_batches_tracked, ema_backbone_layer1_0_conv2_weight, ema_backbone_layer1_0_bn2_weight, ema_backbone_layer1_0_bn2_bias, ema_backbone_layer1_0_bn2_running_mean, ema_backbone_layer1_0_bn2_running_var, ema_backbone_layer1_0_bn2_num_batches_tracked, ema_backbone_layer1_1_conv1_weight, ema_backbone_layer1_1_bn1_weight, ema_backbone_layer1_1_bn1_bias, ema_backbone_layer1_1_bn1_running_mean, ema_backbone_layer1_1_bn1_running_var, ema_backbone_layer1_1_bn1_num_batches_tracked, ema_backbone_layer1_1_conv2_weight, ema_backbone_layer1_1_bn2_weight, ema_backbone_layer1_1_bn2_bias, ema_backbone_layer1_1_bn2_running_mean, ema_backbone_layer1_1_bn2_running_var, ema_backbone_layer1_1_bn2_num_batches_tracked, ema_backbone_layer2_0_conv1_weight, ema_backbone_layer2_0_bn1_weight, ema_backbone_layer2_0_bn1_bias, ema_backbone_layer2_0_bn1_running_mean, ema_backbone_layer2_0_bn1_running_var, ema_backbone_layer2_0_bn1_num_batches_tracked, ema_backbone_layer2_0_conv2_weight, ema_backbone_layer2_0_bn2_weight, ema_backbone_layer2_0_bn2_bias, ema_backbone_layer2_0_bn2_running_mean, ema_backbone_layer2_0_bn2_running_var, ema_backbone_layer2_0_bn2_num_batches_tracked, ema_backbone_layer2_0_downsample_0_weight, ema_backbone_layer2_0_downsample_1_weight, ema_backbone_layer2_0_downsample_1_bias, ema_backbone_layer2_0_downsample_1_running_mean, ema_backbone_layer2_0_downsample_1_running_var, ema_backbone_layer2_0_downsample_1_num_batches_tracked, ema_backbone_layer2_1_conv1_weight, ema_backbone_layer2_1_bn1_weight, ema_backbone_layer2_1_bn1_bias, ema_backbone_layer2_1_bn1_running_mean, ema_backbone_layer2_1_bn1_running_var, ema_backbone_layer2_1_bn1_num_batches_tracked, ema_backbone_layer2_1_conv2_weight, ema_backbone_layer2_1_bn2_weight, ema_backbone_layer2_1_bn2_bias, ema_backbone_layer2_1_bn2_running_mean, ema_backbone_layer2_1_bn2_running_var, ema_backbone_layer2_1_bn2_num_batches_tracked, ema_backbone_layer3_0_conv1_weight, ema_backbone_layer3_0_bn1_weight, ema_backbone_layer3_0_bn1_bias, ema_backbone_layer3_0_bn1_running_mean, ema_backbone_layer3_0_bn1_running_var, ema_backbone_layer3_0_bn1_num_batches_tracked, ema_backbone_layer3_0_conv2_weight, ema_backbone_layer3_0_bn2_weight, ema_backbone_layer3_0_bn2_bias, ema_backbone_layer3_0_bn2_running_mean, ema_backbone_layer3_0_bn2_running_var, ema_backbone_layer3_0_bn2_num_batches_tracked, ema_backbone_layer3_0_downsample_0_weight, ema_backbone_layer3_0_downsample_1_weight, ema_backbone_layer3_0_downsample_1_bias, ema_backbone_layer3_0_downsample_1_running_mean, ema_backbone_layer3_0_downsample_1_running_var, ema_backbone_layer3_0_downsample_1_num_batches_tracked, ema_backbone_layer3_1_conv1_weight, ema_backbone_layer3_1_bn1_weight, ema_backbone_layer3_1_bn1_bias, ema_backbone_layer3_1_bn1_running_mean, ema_backbone_layer3_1_bn1_running_var, ema_backbone_layer3_1_bn1_num_batches_tracked, ema_backbone_layer3_1_conv2_weight, ema_backbone_layer3_1_bn2_weight, ema_backbone_layer3_1_bn2_bias, ema_backbone_layer3_1_bn2_running_mean, ema_backbone_layer3_1_bn2_running_var, ema_backbone_layer3_1_bn2_num_batches_tracked, ema_backbone_layer4_0_conv1_weight, ema_backbone_layer4_0_bn1_weight, ema_backbone_layer4_0_bn1_bias, ema_backbone_layer4_0_bn1_running_mean, ema_backbone_layer4_0_bn1_running_var, ema_backbone_layer4_0_bn1_num_batches_tracked, ema_backbone_layer4_0_conv2_weight, ema_backbone_layer4_0_bn2_weight, ema_backbone_layer4_0_bn2_bias, ema_backbone_layer4_0_bn2_running_mean, ema_backbone_layer4_0_bn2_running_var, ema_backbone_layer4_0_bn2_num_batches_tracked, ema_backbone_layer4_0_downsample_0_weight, ema_backbone_layer4_0_downsample_1_weight, ema_backbone_layer4_0_downsample_1_bias, ema_backbone_layer4_0_downsample_1_running_mean, ema_backbone_layer4_0_downsample_1_running_var, ema_backbone_layer4_0_downsample_1_num_batches_tracked, ema_backbone_layer4_1_conv1_weight, ema_backbone_layer4_1_bn1_weight, ema_backbone_layer4_1_bn1_bias, ema_backbone_layer4_1_bn1_running_mean, ema_backbone_layer4_1_bn1_running_var, ema_backbone_layer4_1_bn1_num_batches_tracked, ema_backbone_layer4_1_conv2_weight, ema_backbone_layer4_1_bn2_weight, ema_backbone_layer4_1_bn2_bias, ema_backbone_layer4_1_bn2_running_mean, ema_backbone_layer4_1_bn2_running_var, ema_backbone_layer4_1_bn2_num_batches_tracked, ema_neck_convs_0_conv_weight, ema_neck_convs_0_conv_bias, ema_bbox_head_sample_x_indexs, ema_bbox_head_prior_feat_ys, ema_bbox_head_prior_ys, ema_bbox_head_seg_decoder_conv_weight, ema_bbox_head_seg_decoder_conv_bias, ema_bbox_head_cls_layers_weight, ema_bbox_head_cls_layers_bias, ema_bbox_head_feat_layer_layers_0_weight, ema_bbox_head_feat_layer_layers_0_bias, ema_bbox_head_feat_layer_layers_1_weight, ema_bbox_head_feat_layer_layers_1_bias, ema_bbox_head_feat_layer_layers_2_weight, ema_bbox_head_feat_layer_layers_2_bias, ema_bbox_head_feat_layer_layers_3_weight, ema_bbox_head_feat_layer_layers_3_bias, ema_bbox_head_fc_reg_layers_0_weight, ema_bbox_head_fc_reg_layers_0_bias, ema_bbox_head_fc_reg_layers_1_weight, ema_bbox_head_fc_reg_layers_1_bias, ema_bbox_head_fc_reg_layers_2_weight, ema_bbox_head_fc_reg_layers_2_bias, ema_bbox_head_fc_reg_layers_3_weight, ema_bbox_head_fc_reg_layers_3_bias, ema_bbox_head_reg_length_weight, ema_bbox_head_reg_length_bias, ema_bbox_head_reg_layers_weight, ema_bbox_head_reg_layers_bias, ema_encoder_layers_0_self_attn_attn_in_proj_weight, ema_encoder_layers_0_self_attn_attn_in_proj_bias, ema_encoder_layers_0_self_attn_attn_out_proj_weight, ema_encoder_layers_0_self_attn_attn_out_proj_bias, ema_encoder_layers_0_ffn_layers_0_0_weight, ema_encoder_layers_0_ffn_layers_0_0_bias, ema_encoder_layers_0_ffn_layers_0_1_weight, ema_encoder_layers_0_ffn_layers_1_weight, ema_encoder_layers_0_ffn_layers_1_bias, ema_encoder_layers_0_norms_0_weight, ema_encoder_layers_0_norms_0_bias, ema_encoder_layers_0_norms_1_weight, ema_encoder_layers_0_norms_1_bias, ema_encoder_layers_1_self_attn_attn_in_proj_weight, ema_encoder_layers_1_self_attn_attn_in_proj_bias, ema_encoder_layers_1_self_attn_attn_out_proj_weight, ema_encoder_layers_1_self_attn_attn_out_proj_bias, ema_encoder_layers_1_ffn_layers_0_0_weight, ema_encoder_layers_1_ffn_layers_0_0_bias, ema_encoder_layers_1_ffn_layers_0_1_weight, ema_encoder_layers_1_ffn_layers_1_weight, ema_encoder_layers_1_ffn_layers_1_bias, ema_encoder_layers_1_norms_0_weight, ema_encoder_layers_1_norms_0_bias, ema_encoder_layers_1_norms_1_weight, ema_encoder_layers_1_norms_1_bias, ema_encoder_layers_2_self_attn_attn_in_proj_weight, ema_encoder_layers_2_self_attn_attn_in_proj_bias, ema_encoder_layers_2_self_attn_attn_out_proj_weight, ema_encoder_layers_2_self_attn_attn_out_proj_bias, ema_encoder_layers_2_ffn_layers_0_0_weight, ema_encoder_layers_2_ffn_layers_0_0_bias, ema_encoder_layers_2_ffn_layers_0_1_weight, ema_encoder_layers_2_ffn_layers_1_weight, ema_encoder_layers_2_ffn_layers_1_bias, ema_encoder_layers_2_norms_0_weight, ema_encoder_layers_2_norms_0_bias, ema_encoder_layers_2_norms_1_weight, ema_encoder_layers_2_norms_1_bias, ema_encoder_layers_3_self_attn_attn_in_proj_weight, ema_encoder_layers_3_self_attn_attn_in_proj_bias, ema_encoder_layers_3_self_attn_attn_out_proj_weight, ema_encoder_layers_3_self_attn_attn_out_proj_bias, ema_encoder_layers_3_ffn_layers_0_0_weight, ema_encoder_layers_3_ffn_layers_0_0_bias, ema_encoder_layers_3_ffn_layers_0_1_weight, ema_encoder_layers_3_ffn_layers_1_weight, ema_encoder_layers_3_ffn_layers_1_bias, ema_encoder_layers_3_norms_0_weight, ema_encoder_layers_3_norms_0_bias, ema_encoder_layers_3_norms_1_weight, ema_encoder_layers_3_norms_1_bias, ema_encoder_layers_4_self_attn_attn_in_proj_weight, ema_encoder_layers_4_self_attn_attn_in_proj_bias, ema_encoder_layers_4_self_attn_attn_out_proj_weight, ema_encoder_layers_4_self_attn_attn_out_proj_bias, ema_encoder_layers_4_ffn_layers_0_0_weight, ema_encoder_layers_4_ffn_layers_0_0_bias, ema_encoder_layers_4_ffn_layers_0_1_weight, ema_encoder_layers_4_ffn_layers_1_weight, ema_encoder_layers_4_ffn_layers_1_bias, ema_encoder_layers_4_norms_0_weight, ema_encoder_layers_4_norms_0_bias, ema_encoder_layers_4_norms_1_weight, ema_encoder_layers_4_norms_1_bias, ema_encoder_layers_5_self_attn_attn_in_proj_weight, ema_encoder_layers_5_self_attn_attn_in_proj_bias, ema_encoder_layers_5_self_attn_attn_out_proj_weight, ema_encoder_layers_5_self_attn_attn_out_proj_bias, ema_encoder_layers_5_ffn_layers_0_0_weight, ema_encoder_layers_5_ffn_layers_0_0_bias, ema_encoder_layers_5_ffn_layers_0_1_weight, ema_encoder_layers_5_ffn_layers_1_weight, ema_encoder_layers_5_ffn_layers_1_bias, ema_encoder_layers_5_norms_0_weight, ema_encoder_layers_5_norms_0_bias, ema_encoder_layers_5_norms_1_weight, ema_encoder_layers_5_norms_1_bias, ema_encoder_query_scale_layers_0_weight, ema_encoder_query_scale_layers_0_bias, ema_encoder_query_scale_layers_1_weight, ema_encoder_query_scale_layers_1_bias, ema_decoder_layers_0_self_attn_qcontent_proj_weight, ema_decoder_layers_0_self_attn_qcontent_proj_bias, ema_decoder_layers_0_self_attn_qpos_proj_weight, ema_decoder_layers_0_self_attn_qpos_proj_bias, ema_decoder_layers_0_self_attn_kcontent_proj_weight, ema_decoder_layers_0_self_attn_kcontent_proj_bias, ema_decoder_layers_0_self_attn_kpos_proj_weight, ema_decoder_layers_0_self_attn_kpos_proj_bias, ema_decoder_layers_0_self_attn_v_proj_weight, ema_decoder_layers_0_self_attn_v_proj_bias, ema_decoder_layers_0_self_attn_out_proj_weight, ema_decoder_layers_0_self_attn_out_proj_bias, ema_decoder_layers_0_cross_attn_qcontent_proj_weight, ema_decoder_layers_0_cross_attn_qcontent_proj_bias, ema_decoder_layers_0_cross_attn_qpos_proj_weight, ema_decoder_layers_0_cross_attn_qpos_proj_bias, ema_decoder_layers_0_cross_attn_kcontent_proj_weight, ema_decoder_layers_0_cross_attn_kcontent_proj_bias, ema_decoder_layers_0_cross_attn_kpos_proj_weight, ema_decoder_layers_0_cross_attn_kpos_proj_bias, ema_decoder_layers_0_cross_attn_v_proj_weight, ema_decoder_layers_0_cross_attn_v_proj_bias, ema_decoder_layers_0_cross_attn_qpos_sine_proj_weight, ema_decoder_layers_0_cross_attn_qpos_sine_proj_bias, ema_decoder_layers_0_cross_attn_out_proj_weight, ema_decoder_layers_0_cross_attn_out_proj_bias, ema_decoder_layers_0_ffn_layers_0_0_weight, ema_decoder_layers_0_ffn_layers_0_0_bias, ema_decoder_layers_0_ffn_layers_0_1_weight, ema_decoder_layers_0_ffn_layers_1_weight, ema_decoder_layers_0_ffn_layers_1_bias, ema_decoder_layers_0_norms_0_weight, ema_decoder_layers_0_norms_0_bias, ema_decoder_layers_0_norms_1_weight, ema_decoder_layers_0_norms_1_bias, ema_decoder_layers_0_norms_2_weight, ema_decoder_layers_0_norms_2_bias, ema_decoder_layers_1_self_attn_qcontent_proj_weight, ema_decoder_layers_1_self_attn_qcontent_proj_bias, ema_decoder_layers_1_self_attn_qpos_proj_weight, ema_decoder_layers_1_self_attn_qpos_proj_bias, ema_decoder_layers_1_self_attn_kcontent_proj_weight, ema_decoder_layers_1_self_attn_kcontent_proj_bias, ema_decoder_layers_1_self_attn_kpos_proj_weight, ema_decoder_layers_1_self_attn_kpos_proj_bias, ema_decoder_layers_1_self_attn_v_proj_weight, ema_decoder_layers_1_self_attn_v_proj_bias, ema_decoder_layers_1_self_attn_out_proj_weight, ema_decoder_layers_1_self_attn_out_proj_bias, ema_decoder_layers_1_cross_attn_qcontent_proj_weight, ema_decoder_layers_1_cross_attn_qcontent_proj_bias, ema_decoder_layers_1_cross_attn_kcontent_proj_weight, ema_decoder_layers_1_cross_attn_kcontent_proj_bias, ema_decoder_layers_1_cross_attn_kpos_proj_weight, ema_decoder_layers_1_cross_attn_kpos_proj_bias, ema_decoder_layers_1_cross_attn_v_proj_weight, ema_decoder_layers_1_cross_attn_v_proj_bias, ema_decoder_layers_1_cross_attn_qpos_sine_proj_weight, ema_decoder_layers_1_cross_attn_qpos_sine_proj_bias, ema_decoder_layers_1_cross_attn_out_proj_weight, ema_decoder_layers_1_cross_attn_out_proj_bias, ema_decoder_layers_1_ffn_layers_0_0_weight, ema_decoder_layers_1_ffn_layers_0_0_bias, ema_decoder_layers_1_ffn_layers_0_1_weight, ema_decoder_layers_1_ffn_layers_1_weight, ema_decoder_layers_1_ffn_layers_1_bias, ema_decoder_layers_1_norms_0_weight, ema_decoder_layers_1_norms_0_bias, ema_decoder_layers_1_norms_1_weight, ema_decoder_layers_1_norms_1_bias, ema_decoder_layers_1_norms_2_weight, ema_decoder_layers_1_norms_2_bias, ema_decoder_layers_2_self_attn_qcontent_proj_weight, ema_decoder_layers_2_self_attn_qcontent_proj_bias, ema_decoder_layers_2_self_attn_qpos_proj_weight, ema_decoder_layers_2_self_attn_qpos_proj_bias, ema_decoder_layers_2_self_attn_kcontent_proj_weight, ema_decoder_layers_2_self_attn_kcontent_proj_bias, ema_decoder_layers_2_self_attn_kpos_proj_weight, ema_decoder_layers_2_self_attn_kpos_proj_bias, ema_decoder_layers_2_self_attn_v_proj_weight, ema_decoder_layers_2_self_attn_v_proj_bias, ema_decoder_layers_2_self_attn_out_proj_weight, ema_decoder_layers_2_self_attn_out_proj_bias, ema_decoder_layers_2_cross_attn_qcontent_proj_weight, ema_decoder_layers_2_cross_attn_qcontent_proj_bias, ema_decoder_layers_2_cross_attn_kcontent_proj_weight, ema_decoder_layers_2_cross_attn_kcontent_proj_bias, ema_decoder_layers_2_cross_attn_kpos_proj_weight, ema_decoder_layers_2_cross_attn_kpos_proj_bias, ema_decoder_layers_2_cross_attn_v_proj_weight, ema_decoder_layers_2_cross_attn_v_proj_bias, ema_decoder_layers_2_cross_attn_qpos_sine_proj_weight, ema_decoder_layers_2_cross_attn_qpos_sine_proj_bias, ema_decoder_layers_2_cross_attn_out_proj_weight, ema_decoder_layers_2_cross_attn_out_proj_bias, ema_decoder_layers_2_ffn_layers_0_0_weight, ema_decoder_layers_2_ffn_layers_0_0_bias, ema_decoder_layers_2_ffn_layers_0_1_weight, ema_decoder_layers_2_ffn_layers_1_weight, ema_decoder_layers_2_ffn_layers_1_bias, ema_decoder_layers_2_norms_0_weight, ema_decoder_layers_2_norms_0_bias, ema_decoder_layers_2_norms_1_weight, ema_decoder_layers_2_norms_1_bias, ema_decoder_layers_2_norms_2_weight, ema_decoder_layers_2_norms_2_bias, ema_decoder_layers_3_self_attn_qcontent_proj_weight, ema_decoder_layers_3_self_attn_qcontent_proj_bias, ema_decoder_layers_3_self_attn_qpos_proj_weight, ema_decoder_layers_3_self_attn_qpos_proj_bias, ema_decoder_layers_3_self_attn_kcontent_proj_weight, ema_decoder_layers_3_self_attn_kcontent_proj_bias, ema_decoder_layers_3_self_attn_kpos_proj_weight, ema_decoder_layers_3_self_attn_kpos_proj_bias, ema_decoder_layers_3_self_attn_v_proj_weight, ema_decoder_layers_3_self_attn_v_proj_bias, ema_decoder_layers_3_self_attn_out_proj_weight, ema_decoder_layers_3_self_attn_out_proj_bias, ema_decoder_layers_3_cross_attn_qcontent_proj_weight, ema_decoder_layers_3_cross_attn_qcontent_proj_bias, ema_decoder_layers_3_cross_attn_kcontent_proj_weight, ema_decoder_layers_3_cross_attn_kcontent_proj_bias, ema_decoder_layers_3_cross_attn_kpos_proj_weight, ema_decoder_layers_3_cross_attn_kpos_proj_bias, ema_decoder_layers_3_cross_attn_v_proj_weight, ema_decoder_layers_3_cross_attn_v_proj_bias, ema_decoder_layers_3_cross_attn_qpos_sine_proj_weight, ema_decoder_layers_3_cross_attn_qpos_sine_proj_bias, ema_decoder_layers_3_cross_attn_out_proj_weight, ema_decoder_layers_3_cross_attn_out_proj_bias, ema_decoder_layers_3_ffn_layers_0_0_weight, ema_decoder_layers_3_ffn_layers_0_0_bias, ema_decoder_layers_3_ffn_layers_0_1_weight, ema_decoder_layers_3_ffn_layers_1_weight, ema_decoder_layers_3_ffn_layers_1_bias, ema_decoder_layers_3_norms_0_weight, ema_decoder_layers_3_norms_0_bias, ema_decoder_layers_3_norms_1_weight, ema_decoder_layers_3_norms_1_bias, ema_decoder_layers_3_norms_2_weight, ema_decoder_layers_3_norms_2_bias, ema_decoder_layers_4_self_attn_qcontent_proj_weight, ema_decoder_layers_4_self_attn_qcontent_proj_bias, ema_decoder_layers_4_self_attn_qpos_proj_weight, ema_decoder_layers_4_self_attn_qpos_proj_bias, ema_decoder_layers_4_self_attn_kcontent_proj_weight, ema_decoder_layers_4_self_attn_kcontent_proj_bias, ema_decoder_layers_4_self_attn_kpos_proj_weight, ema_decoder_layers_4_self_attn_kpos_proj_bias, ema_decoder_layers_4_self_attn_v_proj_weight, ema_decoder_layers_4_self_attn_v_proj_bias, ema_decoder_layers_4_self_attn_out_proj_weight, ema_decoder_layers_4_self_attn_out_proj_bias, ema_decoder_layers_4_cross_attn_qcontent_proj_weight, ema_decoder_layers_4_cross_attn_qcontent_proj_bias, ema_decoder_layers_4_cross_attn_kcontent_proj_weight, ema_decoder_layers_4_cross_attn_kcontent_proj_bias, ema_decoder_layers_4_cross_attn_kpos_proj_weight, ema_decoder_layers_4_cross_attn_kpos_proj_bias, ema_decoder_layers_4_cross_attn_v_proj_weight, ema_decoder_layers_4_cross_attn_v_proj_bias, ema_decoder_layers_4_cross_attn_qpos_sine_proj_weight, ema_decoder_layers_4_cross_attn_qpos_sine_proj_bias, ema_decoder_layers_4_cross_attn_out_proj_weight, ema_decoder_layers_4_cross_attn_out_proj_bias, ema_decoder_layers_4_ffn_layers_0_0_weight, ema_decoder_layers_4_ffn_layers_0_0_bias, ema_decoder_layers_4_ffn_layers_0_1_weight, ema_decoder_layers_4_ffn_layers_1_weight, ema_decoder_layers_4_ffn_layers_1_bias, ema_decoder_layers_4_norms_0_weight, ema_decoder_layers_4_norms_0_bias, ema_decoder_layers_4_norms_1_weight, ema_decoder_layers_4_norms_1_bias, ema_decoder_layers_4_norms_2_weight, ema_decoder_layers_4_norms_2_bias, ema_decoder_layers_5_self_attn_qcontent_proj_weight, ema_decoder_layers_5_self_attn_qcontent_proj_bias, ema_decoder_layers_5_self_attn_qpos_proj_weight, ema_decoder_layers_5_self_attn_qpos_proj_bias, ema_decoder_layers_5_self_attn_kcontent_proj_weight, ema_decoder_layers_5_self_attn_kcontent_proj_bias, ema_decoder_layers_5_self_attn_kpos_proj_weight, ema_decoder_layers_5_self_attn_kpos_proj_bias, ema_decoder_layers_5_self_attn_v_proj_weight, ema_decoder_layers_5_self_attn_v_proj_bias, ema_decoder_layers_5_self_attn_out_proj_weight, ema_decoder_layers_5_self_attn_out_proj_bias, ema_decoder_layers_5_cross_attn_qcontent_proj_weight, ema_decoder_layers_5_cross_attn_qcontent_proj_bias, ema_decoder_layers_5_cross_attn_kcontent_proj_weight, ema_decoder_layers_5_cross_attn_kcontent_proj_bias, ema_decoder_layers_5_cross_attn_kpos_proj_weight, ema_decoder_layers_5_cross_attn_kpos_proj_bias, ema_decoder_layers_5_cross_attn_v_proj_weight, ema_decoder_layers_5_cross_attn_v_proj_bias, ema_decoder_layers_5_cross_attn_qpos_sine_proj_weight, ema_decoder_layers_5_cross_attn_qpos_sine_proj_bias, ema_decoder_layers_5_cross_attn_out_proj_weight, ema_decoder_layers_5_cross_attn_out_proj_bias, ema_decoder_layers_5_ffn_layers_0_0_weight, ema_decoder_layers_5_ffn_layers_0_0_bias, ema_decoder_layers_5_ffn_layers_0_1_weight, ema_decoder_layers_5_ffn_layers_1_weight, ema_decoder_layers_5_ffn_layers_1_bias, ema_decoder_layers_5_norms_0_weight, ema_decoder_layers_5_norms_0_bias, ema_decoder_layers_5_norms_1_weight, ema_decoder_layers_5_norms_1_bias, ema_decoder_layers_5_norms_2_weight, ema_decoder_layers_5_norms_2_bias, ema_decoder_post_norm_weight, ema_decoder_post_norm_bias, ema_decoder_query_scale_layers_0_weight, ema_decoder_query_scale_layers_0_bias, ema_decoder_query_scale_layers_1_weight, ema_decoder_query_scale_layers_1_bias, ema_decoder_ref_point_head_layers_0_weight, ema_decoder_ref_point_head_layers_0_bias, ema_decoder_ref_point_head_layers_1_weight, ema_decoder_ref_point_head_layers_1_bias, ema_decoder_offset_map_layers_0_weight, ema_decoder_offset_map_layers_0_bias, ema_decoder_offset_map_layers_1_weight, ema_decoder_offset_map_layers_1_bias, ema_query_embedding_weight

I have tried all those model.pth, but none of them worked.

**Comment by zkyredstart** [comment]
which mode do you use? inference or train? @Hxiangdou

**Comment by Hxiangdou** [comment]
> which mode do you use? inference or train? @Hxiangdou
inference

**Comment by zkyredstart** [comment]
Could you get the F1 score in the paper after the evaluation? In practice, these mismatched weights come from the EMA training and they have no influence on the inference.

**Comment by Hxiangdou** [comment]
Thanks your reply, I will try again.

**Comment by Hxiangdou** [comment]
Could you provide more information about configs' "ori_img_w = 1640
ori_img_h = 590
img_w = 800
img_h = 320
cut_height = 270"? 
For example, if I want to infer a 1077x617 size image, what should I change? Thanks again.

**Comment by zkyredstart** [comment]
ori_img_h denotes the  height of test image, i.e, 617 for your image. cut height = ori_img_h-img_h, where img_h is the height of input image. Above values are set for CULane dataset.

**Comment by Hxiangdou** [comment]
OK，Thanks for your reply.
