### ISSUE TITLE
训练问题

### ISSUE THREAD

**Issue by SYH9905** [zkyseu/O2SFormer#3]
当我训练时，遇到报错，请问有什么方法可以解决这个问题么
发生异常: ValueError
AdamW: some parameters appear in more than one parameter group
ValueError: some parameters appear in more than one parameter group

During handling of the above exception, another exception occurred:

  File "/wksp/O2SFormer/dnlane/apis/train.py", line 133, in train_detector
    optimizer = build_optimizer(model, cfg.optimizer)
  File "/wksp/O2SFormer/train_net.py", line 244, in main
    meta=meta)
  File "/wksp/O2SFormer/train_net.py", line 248, in <module>
    main()
ValueError: AdamW: some parameters appear in more than one parameter group

**Comment by zkyseu** [comment]
这个问题应该是由PReLU导致的，可以参考这个[PR](https://github.com/open-mmlab/mmcv/pull/2444/commits/4290c68f653f63e96f022f330ceb71b578ee602d)来改一下。这里有一个点就是要找到mmcv在你的环境中位置，然后在 mmcv/cnn/bricks/transformer.py中修改对应行的代码

**Comment by zkyseu** [comment]
因为mmcv1.7.1没有修复PReLU的问题，一般都是要通过这个方法来手动更改

**Comment by SYH9905** [comment]
感谢你的帮助 已经顺利解决这个问题
