### ISSUE TITLE
环境问题:No module named 'mmcv._ext

### ISSUE THREAD

**Issue by Hzy98** [zkyseu/O2SFormer#4]
你好，我看到你论文里说有在3090上测试：
![b6930d4388bf7e08bd5d4d50a322ef1](https://github.com/zkyseu/O2SFormer/assets/77539868/1952fcf8-ef46-4008-9f5e-21d0997577e0)

因为cuda10.2在3090上不适用，所以我改成了11.0，安装对应的pytorch：
conda install pytorch torchvision torchaudio cudatoolkit=11.0 -c pytorch -c nvidia。并根据requiement.tx安装相关包，但是运行时有mmcv的错误：ModuleNotFoundError: No module named 'mmcv._ext'。 看上去是mmcv版本的问题。 能告诉我你3090上环境的相关命令吗？

**Comment by zkyseu** [comment]
@Hzy98 我建议mmcv按照openmmlab公开的[mmcv](https://github.com/open-mmlab/mmcv)官网的命令来安装。mmcv的repo的branch要选择1.x。然后按照他们给的教程按照即可。因为我也发现如果直接pip install  mmcv会有些问题。

**Comment by Hzy98** [comment]
> @Hzy98 我建议mmcv按照openmmlab公开的[mmcv](https://github.com/open-mmlab/mmcv)官网的命令来安装。mmcv的repo的branch要选择1.x。然后按照他们给的教程按照即可。因为我也发现如果直接pip install mmcv会有些问题。

感谢，按照官方命令来装问题解决了。

**Comment by zkyseu** [comment]
@Hzy98 好的，我先关闭这个issue了，如果还有其他问题可以重新打开。
