### ISSUE TITLE
训练问题

### ISSUE THREAD

**Issue by Jed-Zeng** [zkyseu/O2SFormer#5]
请问训练的时候，为什么根据预测的数目来作为不同类别，从而进行多个类别的loss，我看CLRNet在这部分只是0或1分类。如果这样多类别，在自定义数据集中，如果图片车道线分布差别比较大，会有问题的吧？

**Comment by zkyseu** [comment]
@Jed-Zeng 我们使用的是二分类的Focal loss, 相当于给每个车道线类别都训练一个分类器。因为O2SFormer有标签匹配，因此对于不存在的车道线预测会被分配标签为0，真实存在的车道线标签为1。因此，在传入标签的时候，我们就给了真实有效的车道线的位置、角度等信息，然后模型通过标签匹配来获得分类的标签是0还是1。对于车道线分布较大是有影响的。

**Comment by zkyseu** [comment]
如果没有问题的话我先关闭这个issue，如果还有其他问题欢迎重新打开issue哈
