### ISSUE TITLE
数据集读取问题

### ISSUE THREAD

**Issue by Hzy98** [zkyseu/O2SFormer#8]
你好，我看到原始的culane数据是xy型的点坐标。想请问一下代码中是在哪里将一条车道线的点坐标转变为target中78个值。

**Comment by zkyseu** [comment]
@Hzy98  您好，转换代码在[这里](https://github.com/zkyseu/O2SFormer/blob/b0bd8db0822291ad3afbfaf6b4a9e7157c8d62e8/dnlane/datasets/pipelines/lane_formating.py#L658C22-L721)。

**Comment by Hzy98** [comment]
> @Hzy98 您好，转换代码在[这里](https://github.com/zkyseu/O2SFormer/blob/b0bd8db0822291ad3afbfaf6b4a9e7157c8d62e8/dnlane/datasets/pipelines/lane_formating.py#L658C22-L721)。

好的，谢谢您。

**Comment by zkyseu** [comment]
如果有问题可以再次打开issue，我先暂时关闭了
