### ISSUE TITLE
训练时，车道线ground truth标注点转换bug？

### ISSUE THREAD

**Issue by guvcolie** [zkyseu/O2SFormer#9]
您好，我看 https://github.com/zkyseu/O2SFormer/blob/main/dnlane/datasets/pipelines/lane_formating.py#L670 这一行的含义看起来是将1640 X 320尺度下的车道线点坐标转换到 800 X 320尺度下的点坐标，但 x * self.img_w / float(img_w) 这样转换实际上x没有任何变化，只是数据类型转换成了float。 这里是不是有bug？

**Comment by zkyseu** [comment]
@guvcolie 是的哈，只是float，我们的label里面坐标其实并没有归一化，这里其实注释有点错误。但是，你可以在计算loss的时候看到我们会将预测值乘以长或者宽。

**Comment by guvcolie** [comment]
> @guvcolie 是的哈，只是float，我们的label里面坐标其实并没有归一化，这里其实注释有点错误。但是，你可以在计算loss的时候看到我们会将预测值乘以长或者宽。

能附一下 “将预测值乘以长或者宽” 这个逻辑的链接吗

**Comment by zkyseu** [comment]
@guvcolie 在[这里](https://github.com/zkyseu/O2SFormer/blob/b0bd8db0822291ad3afbfaf6b4a9e7157c8d62e8/dnlane/models/detection_headv2.py#L267-L270)
